### ISSUE TITLE
deploy시에 torchserve config를 수정하는 방법이 궁금합니다.

### ISSUE THREAD

**Issue by taepd** [daekeun-ml/end-to-end-pytorch-on-sagemaker#4]
안녕하세요.

torchserve의 dynamic batch를 조정하고 싶은데 어떻게 해당 설정값에 접근해야할지 잘 모르겠습니다.

현재는 default batchsize가 1인 것으로 보이는데 어떻게 하면 이 값을 포함하는 ts-config를 조절할 수 있을까요?

**Comment by daekeun-ml** [comment]
안녕하세요.
SageMaker에서 관리형으로 제공되는 torchserve는 아직까지 server-side batching을 지원하지 않습니다.
(물론 torchserve만 별도로 사용하신다면 server-side batching을 사용할 수 있습니다.)
SageMaker에서 server-side batching을 사용하시려면 SageMaker TF serving을 사용하셔야 합니다.

참고로 해당 설정값은
https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/master/src/sagemaker_pytorch_serving_container/ts_environment.py 에서 확인할 수 있습니다.

**Comment by taepd** [comment]
답변 감사드립니다.

조만간에 server-side batching도 지원했으면 좋겠네요 ㅎㅎ
